blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns =[
    path('', PostLV.as_view(), name='index'),
    re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),name='register_done'),
]

blog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True,
                            help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100,
                                   blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'  # 테이블명 재정의
        ordering = ('-modify_dt',)  # orderby 절, -이면 내림차순

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from blog.models import Post
# Create your views here.

class PostLV(ListView):
    model = Post
    template_name = "blog/post_all.html"
    context_object_name = 'posts'
    paginate_by = 2


class PostDV(DetailView):
    model = Post

mysite/views.py
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


# --- Homepage
class HomeView(TemplateView):
    template_name = 'home.html'


# --- User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')


class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

blog/templates/blog/post_all.html
{% extends "base.html" %}
<h1>Blog List</h1>
<br>
{% block content %}
{%for post in posts%}
 <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
 {{post.modify_dt|date:"N d, Y"}}
 <p>{{post.description}}</p>
{% endfor %}
<br>
<div>
 <span>
 {% if page_obj.has_previous %}
 <a href="?page={{page_obj.previous_page_number}}">Prev</a>
 {% endif %}
 Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}
 {% if page_obj.has_next %}
 <a href="?page={{page_obj.next_page_number}}">Next</a>
 {% endif %}
 </span>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
<h2>{{object.title}}</h2>
<p>
 {%if object.get_previous %}
 <a href="{{object.get_previous.get_absolute_url}}"
 title="이전 글">prev</a>
 {%endif%}
 {%if object.get_next %}
 <a href="{{object.get_next.get_absolute_url}}"
 title="다음 글">next</a>
 {%endif%}
</p>
<p>{{object.modify_dt | date:"j F Y"}}</p>
<br>
<div>
{{object.content | linebreaks}}
</div>

templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <title>{% block title %}Django Web Programming{% endblock %}</title>
 <link rel="stylesheet"
 href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"/>
 <link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
 {% block extra-style %}{% endblock %}
</head>
<body style="padding-top:90px;">
 {% include 'menu.html' %}
 <div class="container">
 {% block content%}{% endblock %}
 </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js">
</script>
{% block extra-script %}{% endblock %}
</html>

templates/home.html
{% extends "base.html" %}
{% block title%}Home{% endblock %}
{% block content%}
<h1>홈 페이지</h1>
{% endblock %}

templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
 <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">
 Django - Python Web Programming</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'blog:index' %}">게시판</a></li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#"
                   data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="">Search</a>
                </div>
            </li>
            <li class="nav-item dropdown mx-1 btn btn-primary">
        {% if user.is_active %}
        <a class="nav-link dropdown-toggle text-white" href="#"
           data-toggle="dropdown">
            <i class="fas fa-user"></i>
            {{user.username }} </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">
                Change Password</a>
        </div>
        {% else %}
        <a class="nav-link dropdown-toggle text-white" href="#"
           data-toggle="dropdown">
            <i class="fas fa-user"></i>Anonymous</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
            <a class="dropdown-item" href="{% url 'register' %}">Register</a>
        </div>
        {% endif %}
    </li>
        </ul>

        <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="search"
                   placeholder="global search" name="search_word">
        </form>
    </div>
</nav>